apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-fleet
  name: fleet-ck2
  namespace: fleet-ck2
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-fleet
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-fleet
    spec:
      containers:
      - image: cklitscherp/fleet:96aa4c978facf0003914fb5e9d4977d48a42cb40
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 80
          name: testck2
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
