apiVersion: v1
kind: Service
metadata:
  name: fleet-service
  namespace: fleet-ck2
spec:
  ports:
  - name: test2
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-fleet
  type: ClusterIP
status:
  loadBalancer: {}
