apiVersion: v1
kind: Service
metadata:
  name: MyApp-service
  namespace: MyApp
spec:
  ports:
  - name: myapp-test
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-MyApp
  type: ClusterIP
status:
  loadBalancer: {}
